use ts_rs::{Config, TS};

#[derive(TS)]
#[ts(export, export_to = "same_file_export/")]
struct DepA {
    foo: i32,
}

#[derive(TS)]
#[ts(export, export_to = "same_file_export/")]
struct DepB {
    foo: i32,
}

#[derive(TS)]
#[ts(export, export_to = "same_file_export/", repr(enum = const_object))]
enum DepC {
    A,
    B,
    C,
}

#[derive(TS)]
#[ts(export, export_to = "same_file_export/types.ts")]
struct A {
    foo: DepA,
}

#[derive(TS)]
#[ts(export, export_to = "same_file_export/types.ts")]
struct B {
    foo: DepB,
}

#[derive(TS)]
#[ts(export, export_to = "same_file_export/types.ts")]
struct C {
    foo: DepA,
    bar: DepB,
    biz: B,
    baz: DepC,
}

#[derive(TS)]
#[ts(export, export_to = "same_file_export/types.ts", repr(enum = const_object))]
enum ConstEnumB {
    B,
}

#[derive(TS)]
#[ts(export_to = "same_file_export/enums.ts", repr(enum))]
enum Bar {
    A,
    B,
}

#[derive(TS)]
#[ts(export_to = "same_file_export/enums.ts", repr(enum))]
enum Foo {
    A,
    B,
}

#[test]
fn export_order() {
    let cfg = Config::from_env();
    Foo::export_all(&cfg);
    Bar::export_all(&cfg);

    let text = super::read_file::<Foo>(&cfg);
    let mut expected = String::with_capacity(1024);

    expected.push_str("// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.\n\n");

    if cfg!(feature = "format") {
        expected.push_str("export enum Bar {\n");
        expected.push_str("  \"A\",\n");
        expected.push_str("  \"B\",\n");
        expected.push_str("}");
        expected.push_str("\n\n");
        expected.push_str("export enum Foo {\n");
        expected.push_str("  \"A\",\n");
        expected.push_str("  \"B\",\n");
        expected.push_str("}\n");
    } else {
        expected.push_str(r#"export enum Bar { "A", "B" }"#);
        expected.push_str("\n\n");
        expected.push_str(r#"export enum Foo { "A", "B" }"#);
        expected.push('\n');
    }

    assert_eq!(text, expected);
}
